#My config
network:
  version: 2
  renderer: networkd
  ethernets:
    usb0:
      dhcp4: true
      dhcp4-overrides:
        hostname: Facade
        route-metric: 0
      addresses: [192.168.10.2/16]
      macaddress: FE:ED:11:FA:CA:DE
  wifis:
    # wfree:
    #   access-points:
    #     opennetwork: {}
    #   dhcp4: yes
    w0:
      dhcp4: true
      dhcp4-overrides:
        hostname: Facade
        route-metric: 0
      addresses: [192.168.10.2/16]
      macaddress: FE:ED:11:FA:CA:DE
      access-points:
        "AllMe":
          password: "00000000"

            # w1:
            #   dhcp4: no
            #   dhcp6: no
            #   addresses: [192.168.0.200/24]
            #   nameservers:
            #     addresses: [192.168.0.1, 8.8.8.8, 208.67.220.220]
            #   access-points:
            #   routes:
            #     - to: default
            #       via: 192.168.0.1
