#!/bin/sh

#Suspend module

if [[ $(systemctl is-active csleep) == "active" ]]; then
    service csleep stop
else
    service csleep start
    sh -c "echo mem > /sys/power/state"
    systemctl restart systemd-networkd && systemctl restart openvpn
fi

while [[ $(systemctl is-active csleep) == "active" ]]; do
    sleep 60
    if [[ $(xprintidle) -gt "60000" ]]; then
        sh -c "echo mem > /sys/power/state"
        systemctl restart systemd-networkd && systemctl restart openvpn
    fi
done
