#!/bin/sh

#Systemd service manipulation module

#1=servicename
systemctl stop $1
systemctl disable $1
rm /etc/systemd/system/$1
rm /usr/lib/systemd/system/$1
systemctl daemon-reload
systemctl reset-failed
