#!/bin/sh

#Browsing web module

curl https://www.example.com/img/v2/[0-100000].jpg -o "#1.jpg" -f

wget -e robots=off -nd --random-wait --limit-rate=300k -r -l 10 -A png,jpg,jpeg -H -D example.com,example.amazonaws.com https://example.com/find-images/
